' Copyright (c) 2026 Bruce A Henderson
' 
' Permission is hereby granted, free of charge, to any person obtaining a copy
' of this software and associated documentation files (the "Software"), to deal
' in the Software without restriction, including without limitation the rights
' to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
' copies of the Software, and to permit persons to whom the Software is
' furnished to do so, subject to the following conditions:
' 
' The above copyright notice and this permission notice shall be included in
' all copies or substantial portions of the Software.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
' IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
' FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
' AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
' LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
' OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
' THE SOFTWARE.
' 
SuperStrict

Import "flecs/include/*.h"

Import "flecs/src/addons/alerts.c"
Import "flecs/src/addons/doc.c"
Import "flecs/src/addons/flecs_cpp.c"
Import "flecs/src/addons/http/http.c"
Import "flecs/src/addons/journal.c"
Import "flecs/src/addons/json/deserialize_value.c"
Import "flecs/src/addons/json/deserialize.c"
Import "flecs/src/addons/json/json.c"
Import "flecs/src/addons/json/serialize_entity.c"
Import "flecs/src/addons/json/serialize_field_info.c"
Import "flecs/src/addons/json/serialize_iter_result_query.c"
Import "flecs/src/addons/json/serialize_iter_result_table.c"
Import "flecs/src/addons/json/serialize_iter_result.c"
Import "flecs/src/addons/json/serialize_iter.c"
Import "flecs/src/addons/json/serialize_query_info.c"
Import "flecs/src/addons/json/serialize_type_info.c"
Import "flecs/src/addons/json/serialize_value.c"
Import "flecs/src/addons/json/serialize_world.c"
Import "flecs/src/addons/query_dsl/parser.c"
Import "flecs/src/addons/stats/memory.c"
Import "flecs/src/addons/stats/monitor.c"
Import "flecs/src/addons/stats/pipeline_monitor.c"
Import "flecs/src/addons/stats/stats.c"
Import "flecs/src/addons/stats/system_monitor.c"
Import "flecs/src/addons/stats/world_monitor.c"
Import "flecs/src/addons/stats/world_summary.c"
Import "flecs/src/addons/log.c"
Import "flecs/src/addons/meta/definitions.c"
Import "flecs/src/addons/meta/meta.c"
Import "flecs/src/addons/meta/cursor.c"
Import "flecs/src/addons/meta/serializer.c"
Import "flecs/src/addons/meta/rtt_lifecycle.c"
Import "flecs/src/addons/meta/c_utils.c"
Import "flecs/src/addons/meta/type_support/array_ts.c"
Import "flecs/src/addons/meta/type_support/enum_ts.c"
Import "flecs/src/addons/meta/type_support/opaque_ts.c"
Import "flecs/src/addons/meta/type_support/primitive_ts.c"
Import "flecs/src/addons/meta/type_support/struct_ts.c"
Import "flecs/src/addons/meta/type_support/units_ts.c"
Import "flecs/src/addons/metrics.c"
Import "flecs/src/addons/module.c"
Import "flecs/src/addons/os_api_impl/os_api_impl.c"
Import "flecs/src/addons/parser/tokenizer.c"
Import "flecs/src/addons/pipeline/frame.c"
Import "flecs/src/addons/pipeline/pipeline.c"
Import "flecs/src/addons/pipeline/worker.c"
Import "flecs/src/addons/rest.c"
Import "flecs/src/addons/script/template.c"
Import "flecs/src/addons/script/ast.c"
Import "flecs/src/addons/script/function.c"
Import "flecs/src/addons/script/functions_builtin.c"
Import "flecs/src/addons/script/functions_math_perlin.c"
Import "flecs/src/addons/script/functions_math.c"
Import "flecs/src/addons/script/parser.c"
Import "flecs/src/addons/script/script.c"
Import "flecs/src/addons/script/serialize.c"
Import "flecs/src/addons/script/template.c"
Import "flecs/src/addons/script/vars.c"
Import "flecs/src/addons/script/visit_check.c"
Import "flecs/src/addons/script/visit_eval.c"
Import "flecs/src/addons/script/visit_free.c"
Import "flecs/src/addons/script/visit_to_str.c"
Import "flecs/src/addons/script/visit.c"
Import "flecs/src/addons/script/expr/ast.c"
Import "flecs/src/addons/script/expr/parser.c"
Import "flecs/src/addons/script/expr/stack.c"
Import "flecs/src/addons/script/expr/util.c"
Import "flecs/src/addons/script/expr/visit_eval.c"
Import "flecs/src/addons/script/expr/visit_fold.c"
Import "flecs/src/addons/script/expr/visit_free.c"
Import "flecs/src/addons/script/expr/visit_to_str.c"
Import "flecs/src/addons/script/expr/visit_type.c"
Import "flecs/src/addons/system/system.c"
Import "flecs/src/addons/timer.c"
Import "flecs/src/addons/units.c"

Import "flecs/src/datastructures/allocator.c"
Import "flecs/src/datastructures/bitset.c"
Import "flecs/src/datastructures/block_allocator.c"
Import "flecs/src/datastructures/hash.c"
Import "flecs/src/datastructures/hashmap.c"
Import "flecs/src/datastructures/map.c"
Import "flecs/src/datastructures/stack_allocator.c"
Import "flecs/src/datastructures/name_index.c"
Import "flecs/src/datastructures/sparse.c"
Import "flecs/src/datastructures/strbuf.c"
Import "flecs/src/datastructures/vec.c"

Import "flecs/src/storage/component_index.c"
Import "flecs/src/storage/entity_index.c"
Import "flecs/src/storage/non_fragmenting_childof.c"
Import "flecs/src/storage/ordered_children.c"
Import "flecs/src/storage/sparse_storage.c"
Import "flecs/src/storage/table.c"
Import "flecs/src/storage/table_cache.c"
Import "flecs/src/storage/table_graph.c"

Import "flecs/src/query/cache/cache_iter.c"
Import "flecs/src/query/cache/cache.c"
Import "flecs/src/query/cache/change_detection.c"
Import "flecs/src/query/cache/group.c"
Import "flecs/src/query/cache/match.c"
Import "flecs/src/query/cache/order_by.c"
Import "flecs/src/query/compiler/compiler_term.c"
Import "flecs/src/query/compiler/compiler.c"
Import "flecs/src/query/engine/eval_iter.c"
Import "flecs/src/query/engine/eval_member.c"
Import "flecs/src/query/engine/eval_pred.c"
Import "flecs/src/query/engine/eval_sparse.c"
Import "flecs/src/query/engine/eval_toggle.c"
Import "flecs/src/query/engine/eval_trav.c"
Import "flecs/src/query/engine/eval_tree.c"
Import "flecs/src/query/engine/eval_up.c"
Import "flecs/src/query/engine/eval_utils.c"
Import "flecs/src/query/engine/eval.c"
Import "flecs/src/query/engine/trav_cache.c"
Import "flecs/src/query/engine/trav_down_cache.c"
Import "flecs/src/query/engine/trav_up_cache.c"
Import "flecs/src/query/engine/trivial_iter.c"
Import "flecs/src/query/api.c"
Import "flecs/src/query/util.c"
Import "flecs/src/query/validator.c"

Import "flecs/src/bootstrap.c"
Import "flecs/src/commands.c"
Import "flecs/src/component_actions.c"
Import "flecs/src/each.c"
Import "flecs/src/entity_name.c"
Import "flecs/src/entity.c"
Import "flecs/src/id.c"
Import "flecs/src/instantiate.c"
Import "flecs/src/iter.c"
Import "flecs/src/misc.c"
Import "flecs/src/observable.c"
Import "flecs/src/observer.c"
Import "flecs/src/on_delete.c"
Import "flecs/src/os_api.c"
Import "flecs/src/poly.c"
Import "flecs/src/ref.c"
Import "flecs/src/stage.c"
Import "flecs/src/search.c"
Import "flecs/src/tree_spawner.c"
Import "flecs/src/type_info.c"
Import "flecs/src/value.c"
Import "flecs/src/world.c"

Import "glue.c"
